### ISSUE TITLE
노션 페이지 잠금 요청

### ISSUE THREAD

**Issue by us03164** [PreswotLab/preswotlab#1]
@koreanddinghwan 
안녕하세요 명환님!
다름이 아니라 현재 노션 페이지가 누구나 수정 가능하게 되어 있는 것 같아서요!
누구나 접근은 가능하되 수정은 불가능하게 되어야 할 것 같습니다.
팀 페이지로 전환하거나 그때 공유(?)한 계정들만 수정 가능하게 변경하는 게 어떨까요?

**Comment by koreanddinghwan** [comment]
앗 제가 지금 예비군 와있는데 데이터가 느려서요 ㅠㅠ 집가서 바꾸겠습니다!

**Comment by us03164** [comment]
> 앗 제가 지금 예비군 와있는데 데이터가 느려서요 ㅠㅠ 집가서 바꾸겠습니다!

아니 이걸 이렇게 빨리 응답한다고요? 그것도 예비군에서?? ㅋㅋㅋㅋㅋㅋ
천천히 하셔도 돼요~

**Comment by koreanddinghwan** [comment]
헤헷 감사합니당

**Comment by koreanddinghwan** [comment]
일단 잠금은 해놨습니다. 이메일 주시면 편집가능하게 설정드리겠습니다
